further attempts to get Josh's continuity program working ... still doesn't
ghost admixture had to comment out the time_out_errors.write function call as pickle couldn't pickle it when sending it out for multiprocessing

still ends up giving an error:

"""
Traceback (most recent call last):
  File "/home/dlawrie/miniconda3/envs/fwdpy11_arg/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 421, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/dlawrie/miniconda3/envs/fwdpy11_arg/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 563, in __call__
    return self.func(*args, **kwargs)
  File "/home/dlawrie/miniconda3/envs/fwdpy11_arg/lib/python3.6/site-packages/joblib/parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "/home/dlawrie/miniconda3/envs/fwdpy11_arg/lib/python3.6/site-packages/joblib/parallel.py", line 261, in <listcomp>
    for func, args, kwargs in self.items]
  File "run_ghost_admixture_continuity_job.py", line 28, in sim_ghost_admixture
    params_pop_sim_free = optimize_pop_params_error_parallel(freqs_sim,read_list_sim,num_core=1,detail=0,continuity=False)
  File "/home/dlawrie/Dropbox/fwdpy11_arg_example/ancient_genotypes.py", line 419, in optimize_pop_params_error_parallel
    min_a, max_a, min_d, max_d = get_bounds_reads(read_lists)
  File "/home/dlawrie/Dropbox/fwdpy11_arg_example/ancient_genotypes.py", line 317, in get_bounds_reads
    max_a.append(max(map(lambda x: np.amax(x[:,:,0]),reads[i])))
ValueError: max() arg is an empty sequence
"""

test_evolve gives same error when updated to ghost_admixture's  read output and run_continuity fails at get_read_dict